--此脚本用来生成数据库中的表，并插入一些必要的数据

--分类表
CREATE TABLE T_CATEGORY (
CID NUMBER PRIMARY KEY NOT NULL ,
CNAME VARCHAR2(255 BYTE) NULL 
);
INSERT INTO T_CATEGORY VALUES ('1', '四级词汇');
INSERT INTO T_CATEGORY VALUES ('2', '六级词汇');
INSERT INTO T_CATEGORY VALUES ('3', '例句');
--四级单词表
CREATE TABLE T_CET4 (
FID NUMBER PRIMARY KEY NOT NULL,
FWORD VARCHAR2(255 BYTE),
FMEAN  VARCHAR2(255 BYTE),
DIFF NUMBER,
COMMON NUMBER,
CID NUMBER REFERENCES T_CATEGORY(CID)
);
INSERT INTO T_CET4 VALUES ('1', 'a', '一个', '1', '0', '1');
--六级单词表
CREATE TABLE T_CET6 (
SID NUMBER PRIMARY KEY NOT NULL,
SWORD VARCHAR2(255 BYTE),
SMEAN  VARCHAR2(255 BYTE),
DIFF NUMBER,
COMMON NUMBER,
CID NUMBER REFERENCES T_CATEGORY(CID)
);
INSERT INTO T_CET6 VALUES ('1', 'a', '一个', '1', '0', '2');
--例句表
CREATE TABLE T_PHRASE (
PID NUMBER PRIMARY KEY NOT NULL,
PSENTENCE VARCHAR2(255 BYTE),
PMEAN  VARCHAR2(255 BYTE),
DIFF NUMBER,
COMMON NUMBER,
CID NUMBER REFERENCES T_CATEGORY(CID)
);
INSERT INTO T_PHRASE VALUES ('1', 'a', '一个', '1', '0', '3');
--用户表
CREATE TABLE T_USER (
USERID NUMBER PRIMARY KEY NOT NULL,
EMAIL VARCHAR2(255 BYTE),
UNAME  VARCHAR2(255 BYTE),
PASSWORD VARCHAR2(255 BYTE)
);
INSERT INTO T_USER VALUES ('1', 'test@zc.com', '张超', '123456');
--翻译表
CREATE TABLE T_TRAN (
TID NUMBER PRIMARY KEY NOT NULL,
TWORD VARCHAR2(255 BYTE),
TMEAN  VARCHAR2(255 BYTE)
);

